version: '3'
services:
  app:
    image: node:18.12.1-alpine
    container_name: app
    ports:
      - 5173:5173
      - 3000:3000
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "yarn install && yarn start"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:123456@db:5432/NgCash
  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

